spring:
  datasource:
    generate-unique-name: false
    name:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile
logging:
  level:
   root: WARN
   org.springframework.security: DEBUG

taco:
  orders:
    pageSize: 20